### ISSUE TITLE
编译缺少资源文件 Bin/Shaders  Bin/Images

### ISSUE THREAD

**Issue by kkzi** [yiyaowen/D14UIKit#1]
编译环境：Windows 10 22H2, Visual Studio 2022 17.7.4

![image](https://github.com/yiyaowen/D14UIKit/assets/34122458/e082e1d7-47bd-4bd3-ae54-4bf8188c7aa7)

为大佬的工作点赞

**Comment by yiyaowen** [comment]
你好，这个项目的大文件都保管在服务器上，下载地址为：
https://d14games.com/downloads/developer/D14UIKit.zip
（由于还没有安装证书，浏览器可能会提示继续访问）

关于如何修改和构建项目的具体细节可以在这里找到：
https://d14engine.com/zh_CN/latest/exprojs/d14uikit/devs/index.html

目前也有一些简单的使用教程，后续随着开发会继续更新：
https://d14engine.com/zh_CN/latest/exprojs/d14uikit/tutorials/hello_window.html

**Comment by kkzi** [comment]
好的，了解了
